-- Task 78 — Notification Integrations & emailing from Snowflake
-- Category: Programmability
--
-- Goal: Sending email from Snowflake via a Notification Integration and SYSTEM$SEND_EMAIL -- wiring an Alert or Task to actually page someone.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
