-- Task 21 — OBJECT data type
-- Category: Semi-structured data
--
-- Goal: Storing and querying key-value data natively with OBJECT.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
