-- Task 7 — ON_ERROR = SKIP_FILE_<percent>%
-- Category: Loading & COPY options
--
-- Goal: Tolerating a percentage of bad rows per file instead of a fixed count.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
