-- Task 59 — Retention & storage cost
-- Category: Time Travel & cloning
--
-- Goal: How DATA_RETENTION_TIME_IN_DAYS drives storage cost for Time Travel and Fail-safe.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
