-- Task 81 — PUT/GET/REMOVE file commands
-- Category: Stages & File Management
--
-- Goal: Uploading, downloading, and removing files on a stage with PUT/GET/REMOVE from the command line, instead of Snowsight's upload UI.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
