-- Task 39 — Monitoring (PIPE_STATUS, SYSTEM$PIPE_STATUS)
-- Category: Snowpipe
--
-- Goal: Checking whether a pipe is healthy and what's queued or failed.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
