-- Task 117 — SnowPro Core review
-- Category: Cert & interview prep
--
-- Goal: Working through SnowPro Core exam-style questions against concepts from earlier tasks.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
