-- Task 30 — Snowpipe cost model
-- Category: Snowpipe
--
-- Goal: How Snowpipe billing (serverless compute per file) differs from warehouse billing.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
