-- Task 48 — Transforming data mid-COPY
-- Category: Loading & COPY options
--
-- Goal: Using a SELECT inside COPY INTO to reshape columns during the load instead of after.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
