-- Task 63 — Comparing two tables for drift
-- Category: Data Integrity & Quality
--
-- Goal: Comparing two tables (e.g. QA vs. prod) for drift with MINUS/EXCEPT and hash-based row comparison.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
