-- Task 66 — Snowflake Cortex
-- Category: Ecosystem
--
-- Goal: Calling Cortex's built-in LLM functions directly from SQL.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
