-- Task 106 — dbt schema tests (unique, not_null, relationships, accepted_values)
-- Category: dbt
--
-- Goal: The four built-in generic tests declared in YAML, and what each one actually catches.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
