-- Task 74 — Iceberg Tables
-- Category: Newer table types
--
-- Goal: Snowflake reading/writing the open Iceberg table format on external storage.
--
-- TODO: write the walkthrough SQL for this task.

-- ============================================================
-- Understanding check (answer after running the above)
-- ============================================================
-- 1. TODO
-- 2. TODO
-- 3. TODO
